### ISSUE TITLE
Server does not restart

### ISSUE THREAD

**Issue by 34j** [microsoft/vscode-python-tools-extension-template#58]
The first time LSP starts up, it works correctly, but after running command `Restart Server` (or editing Settings), it stops in the following areas in the VSCode `OUTPUT`:

```
Server Command [RUN]: c:\Users...python.exe c:\Users...server.py
Server Command [DEBUG]: c:\Users...python.exe c:\Users..._debug_server.py
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x0000029B83B57760>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
```

After that, the server does not start forever and no output will be produced.

I found that this issue is caused by #48 
 ( [ada4b5ab9f1552e0cc5408302e1c559057f25ea4](https://github.com/microsoft/vscode-python-tools-extension-template/commit/ada4b5ab9f1552e0cc5408302e1c559057f25ea4)) and can be fixed by reverting the `createServer()` code in `src/common/server.ts`. The `OUTPUT` will be as follows.

```
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x000001AFFD633250>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
CWD Server: c:\Users...
```

**Comment by karthiknadig** [comment]
Duplicate of https://github.com/microsoft/vscode-python-tools-extension-template/issues/46
